### ISSUE TITLE
ReferenceError: window is not defined in node_modules/monolite/lib/monolite/index.js:1

### ISSUE THREAD

**Issue by ellis** [kube/monolite#46]
I just installed the latest version of monolite, but when I import it into a script, I get the following error:

```
ReferenceError: window is not defined

/.../node_modules/monolite/lib/monolite/index.js:1
```

If I edit index.js and replace the one instance of `window` with `{}`, then everything runs as expected.  Any idea why the superfluous `window` reference is in index.js?

Cheers!

**Comment by medfreeman** [comment]
Hi, would you accept a PR containing the suggested change ?

**Comment by kube** [comment]
@medfreeman Sorry, just coming back here. (Gonna try to keep my Github notifications clean for now on)
If you are still interested of course, I would be happy to see people contributions.
I really need to update and maintain this library though.

**Comment by kube** [comment]
This is because of https://github.com/webpack/webpack/issues/6522
I'm gonna create a fix for it. (I did update all packages this weekend, and did setup automatic NPM publish to be able to be able to update easily this library.

**Comment by medfreeman** [comment]
Nice, thanks a lot!

**Comment by kube** [comment]
Should be fixed now.
I know it's been a long time since the issue creation, but do not hesitate to come back creating an issue if you face any issue with the library.

**Comment by medfreeman** [comment]
With 0.9.0, i still get the error while calling the function:
```
ReferenceError: window is not defined
[redacted module]:     at Object.<anonymous> (/[redacted path]/node_modules/monolite/dist/index.js:1)
```

**Comment by kube** [comment]
Ok there was an issue with deployment.
Should be fine now. I tested it manually from CodeSandbox both on Node and Browser.

Thanks for your report.
